name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ReminderTabletNew2/ReminderTabletNew2.csproj
      
    - name: Build
      run: dotnet build ReminderTabletNew2/ReminderTabletNew2.csproj --no-restore -c Release
      
    - name: Publish
      run: dotnet publish ReminderTabletNew2/ReminderTabletNew2.csproj -c Release -o release --nologo
      
    - name: Change base-tag in index.html
      run: |
        sed -i 's/<base href="\/" \/>/<base href="\/ReminderApp\/" \/>/g' release/wwwroot/index.html
        
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './release/wwwroot'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 