# Deploy .NET Functions to Azure
name: Deploy .NET Functions to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'ReminderApp.Functions/**'
      - '.github/workflows/deploy-functions.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'reminderapp-functions-hrhddjfeb0bpa0ee'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Restore dependencies'
      shell: bash
      run: |
        cd ReminderApp.Functions
        dotnet restore

    - name: 'Build and Publish'
      shell: bash
      run: |
        cd ReminderApp.Functions
        dotnet publish ReminderApp.Functions.csproj -c Release -o ./output
        
    - name: 'Create deployment ZIP'
      shell: bash
      run: |
        cd ReminderApp.Functions/output
        zip -r ../deploy.zip .
        
    - name: 'Extract publish credentials from profile'
      id: publishcreds
      shell: bash
      run: |
        PUBLISH_PROFILE='${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}'
        
        # Extract username (Kudu username)
        USERNAME=$(echo "$PUBLISH_PROFILE" | grep -oP 'userName="\K[^"]+' | head -1)
        
        # Extract password (Kudu password)
        PASSWORD=$(echo "$PUBLISH_PROFILE" | grep -oP 'userPWD="\K[^"]+' | head -1)
        
        # Extract publish URL (Kudu URL)
        KUDU_URL=$(echo "$PUBLISH_PROFILE" | grep -oP 'publishUrl="\K[^"]+' | grep -i scm | head -1)
        
        echo "username=$USERNAME" >> $GITHUB_OUTPUT
        echo "password=$PASSWORD" >> $GITHUB_OUTPUT
        echo "kudu_url=https://$KUDU_URL" >> $GITHUB_OUTPUT
        
    - name: 'Deploy to Azure Functions via Kudu'
      shell: bash
      run: |
        curl -X POST \
          -u "${{ steps.publishcreds.outputs.username }}:${{ steps.publishcreds.outputs.password }}" \
          --data-binary @"ReminderApp.Functions/deploy.zip" \
          "${{ steps.publishcreds.outputs.kudu_url }}/api/zipdeploy" \
          -H "Content-Type: application/zip" \
          -v
        
    - name: 'Remove WEBSITE_RUN_FROM_PACKAGE via Kudu'
      shell: bash
      run: |
        echo "Removing WEBSITE_RUN_FROM_PACKAGE to allow direct deployment..."
        curl -X DELETE \
          -u "${{ steps.publishcreds.outputs.username }}:${{ steps.publishcreds.outputs.password }}" \
          "${{ steps.publishcreds.outputs.kudu_url }}/api/settings/WEBSITE_RUN_FROM_PACKAGE" \
          || echo "Setting not found or already removed"
        
    - name: 'Restart Function App via Kudu'
      shell: bash
      run: |
        echo "Restarting Function App to load new deployment..."
        curl -X POST \
          -u "${{ steps.publishcreds.outputs.username }}:${{ steps.publishcreds.outputs.password }}" \
          "${{ steps.publishcreds.outputs.kudu_url }}/api/restart" \
          || echo "Restart requested"
        
    - name: 'Test API Endpoints'
      shell: bash
      run: |
        echo "Waiting for deployment to complete..."
        sleep 60
        echo "Testing Health Check endpoint..."
        curl -f "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/health" || echo "Health check failed"
        echo "Testing ReminderAPI endpoint..."
        curl -f "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/ReminderAPI?clientID=test" || echo "ReminderAPI test failed"
        echo "Testing Admin Dashboard..."
        curl -f "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/admin" || echo "Admin dashboard test failed"
