# Deploy .NET Functions to Azure
name: Deploy .NET Functions to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'reminderapp-functions'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build and Publish'
      shell: bash
      run: |
        dotnet publish ReminderApp.Functions/ReminderApp.Functions.csproj --configuration Release --output ReminderApp.Functions/output

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_611B833E45674DB8892A05A29A43CFE8 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_53C095154474464AB1A28EB927FF7ED4 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_824E2AC54D7A4FDCB8E84BB0CA0DDD57 }}

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: 'ReminderApp.Functions/output'
